### ISSUE TITLE
writing fails

### ISSUE THREAD

**Issue by NNEU-1** [amrbekhit/microchipboot#1]
Hi,

Thanks for this project!
I've been trying it out today and found that there is some issue with the transmission. Not always, but most times.
It sais "failed to write flash at address" at some random address. Sometimes sooner, sometimes later, sometimes it doesn't fail at all.

It seems that its more likely to fail at higher baude rates, but there is no baude rate that works reliably. 
With the official Java version it every single time, even at 115200 baude rate. 

Have you made any similar experiences ?

**Comment by amrbekhit** [comment]
Hello, I believe the problem you were facing was due to a bug in the serial receive function, which has now been fixed in the [latest release 0.3.1](https://github.com/amrbekhit/microchipboot/releases/tag/v0.3.1).
